apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: codescan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codescan
  template:
    metadata:
      labels:
        app: codescan
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  selector:
    app: codescan
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
