apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
    tier: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        tier: devops
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:centos
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
    tier: devops
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
