apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfrog
  labels:
    app: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: jfrog
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        resources:
          limits:
            memory: "4Gi"
            cpu: "1000m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: jfrog
spec:
  selector:
    app: artifactory
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
